import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-low": "#f6f3f5",
        "on-secondary-fixed": "#002114",
        "on-error-container": "#93000a",
        "tertiary-fixed": "#dae2fd",
        "on-secondary-fixed-variant": "#005137",
        "error-container": "#ffdad6",
        "secondary-fixed-dim": "#68dba9",
        "primary-container": "#131b2e",
        "on-tertiary-fixed-variant": "#3f465c",
        "primary-fixed-dim": "#bec6e0",
        "tertiary": "#000000",
        "pure-surface": "#ffffff",
        "surface-container": "#f0edef",
        "on-surface": "#1b1b1d",
        "inverse-primary": "#bec6e0",
        "surface-container-highest": "#e4e2e4",
        "on-tertiary-container": "#7c839b",
        "muted-steel": "#4b5563",
        "secondary-container": "#82f5c1",
        "background": "#fcf8fa",
        "on-secondary-container": "#00714e",
        "inverse-on-surface": "#f3f0f2",
        "surface": {
          DEFAULT: "#fcf8fa",
          dim: "#dcd9db",
          bright: "#fcf8fa",
          bg: "#f9fafb",
        },
        "secondary": "#006c4a",
        "error": "#ba1a1a",
        "on-secondary": "#ffffff",
        "primary": {
          DEFAULT: "#251544",
          inverse: "#ffffff",
          fixed: "#eaddff",
          dim: "#d1bdf7",
          container: "#3b2b5b",
        },
        "surface-tint": "#565e74",
        "on-primary-fixed-variant": "#3f465c",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed": "#85f8c4",
        "on-error": "#ffffff",
        "emerald-trust": "#059669",
        "whisper-border": "#e5e7eb",
        "deep-slate": "#0f172a",
        "canvas-white": "#f9fafb",
        "tertiary-container": "#131b2e",
        "surface-container-high": "#eae7e9",
        "on-background": "#1b1b1d",
        "outline-variant": "#c6c6cd",
        "outline": "#76777d",
        "on-tertiary-fixed": "#131b2e",
        "on-surface-variant": "#45464d",
        "surface-variant": "#e4e2e4",
        "on-primary-container": "#7c839b",
        "on-primary-fixed": "#131b2e",
        "on-primary": "#ffffff",
        "inverse-surface": "#303032",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "margin-desktop": "48px",
        "margin-mobile": "16px",
        "stack-md": "16px",
        "section-gap": "80px",
        "container-max": "1440px",
        "stack-sm": "8px",
        "gutter": "24px",
        "stack-lg": "32px",
      },
      fontFamily: {
        "label-sm": ["JetBrains Mono"],
        "headline-xl-mobile": ["Outfit"],
        "body-md": ["Hanken Grotesk", "Satoshi"],
        "body-lg": ["Hanken Grotesk", "Satoshi"],
        "headline-md": ["Outfit"],
        "headline-xl": ["Outfit"],
        "headline-lg": ["Outfit"],
        "mono-num": ["JetBrains Mono"],
        display: ["Outfit", "sans-serif"],
        sans: ["Hanken Grotesk", "Satoshi", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "label-sm": ["12px", { lineHeight: "1.0", letterSpacing: "0.05em", fontWeight: "500" }],
        "headline-xl-mobile": ["40px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "500" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-md": ["32px", { lineHeight: "1.3", letterSpacing: "-0.01em", fontWeight: "500" }],
        "headline-xl": ["64px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "500" }],
        "headline-lg": ["40px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "500" }],
      },
      boxShadow: {
        whisper: "0 4px 20px rgba(0, 0, 0, 0.03)",
        "whisper-hover": "0 10px 40px rgba(0, 0, 0, 0.05)",
      },
    },
  },
  plugins: [],
};
export default config;
